from rest_framework import serializers
# Import the serializers module from Django REST Framework (DRF) to handle data conversion.

class ItemSerializer(serializers.Serializer):
    """
    ITEM SERIALIZER
    
    Analogy:
    Think of a Serializer like a translator at a customs desk.
    Our database stores raw records, but the frontend needs them as standard JSON text.
    The Serializer translates our Python database objects into clean JSON dictionaries,
    and checks if incoming user data is valid before saving it.
    """
    
    # id: The unique database primary key. Read-only because it's automatically generated by Django.
    id = serializers.IntegerField(read_only=True)
    
    # name: The name of the tech gadget.
    name = serializers.CharField()
    
    # brand: The manufacturer of the gadget.
    brand = serializers.CharField()
    
    # category: The type of gadget, e.g., Headphones, Laptops, or Cameras.
    category = serializers.CharField()
    
    # description: A detailed description explaining the gadget's specifications.
    description = serializers.CharField()
    
    # image_url: A web link pointing to the product cover image.
    image_url = serializers.CharField(required=False, allow_blank=True)
    
    # price: The listed price. We specify max_digits and decimal_places to preserve decimal formatting.
    price = serializers.DecimalField(max_digits=10, decimal_places=2)
    
    # avg_rating: The average rating score (1-5) calculated dynamically across all reviews.
    # We use FloatField since it can contain decimals (e.g. 4.5) and allow_null=True if there are no reviews yet.
    avg_rating = serializers.FloatField(allow_null=True)
    
    # review_count: The total count of reviews written for this specific gadget.
    review_count = serializers.IntegerField()


class ReviewSerializer(serializers.Serializer):
    """
    REVIEW SERIALIZER
    
    Analogy:
    Think of the ReviewSerializer like a passport translator for a visitor's comment card.
    It takes the rating, text body, and vote counts, compiles them alongside the reviewer's 
    name and profile picture, and converts it into a standard JSON package for the frontend.
    """
    
    # id: The unique review database ID. Read-only since it is generated by Django.
    id = serializers.IntegerField(read_only=True)
    
    # rating: The star rating score given by the user (1 to 5).
    rating = serializers.IntegerField()
    
    # body: The detailed feedback comments submitted by the user.
    body = serializers.CharField()
    
    # upvote_count: The total count of community members who marked this review helpful.
    upvote_count = serializers.IntegerField()
    
    # has_voted: A true/false flag indicating if the logged-in user personally voted for this review.
    has_voted = serializers.BooleanField()
    
    # created_at: Timestamp recording when the review was written. Read-only.
    created_at = serializers.DateTimeField(read_only=True)
    
    # author_name: The display name or email address of the user who wrote the review.
    author_name = serializers.CharField()
    
    author_avatar = serializers.CharField(required=False, allow_blank=True)


class ReviewCreateSerializer(serializers.Serializer):
    """
    REVIEW CREATE SERIALIZER
    
    Analogy:
    Think of this like an application form filled out by a visitor.
    Before we let them submit their opinion, we check if they filled it out correctly:
    - Did they give a rating score between 1 and 5?
    - Did they write a long enough comment (at least 10 characters)?
    Unlike the ReviewSerializer which translates database records for the browser,
    this serializer's job is to inspect incoming data from the user and ensure it's safe and complete.
    """
    
    # rating: The star rating value from 1 to 5.
    # min_value=1 and max_value=5 enforce that they can't submit an invalid rating score.
    rating = serializers.IntegerField(min_value=1, max_value=5)
    
    # body: The text of the review.
    # min_length=10 ensures the reviewer writes a meaningful message instead of just a single letter.
    body = serializers.CharField(min_length=10)


