from rest_framework import serializers
# Import the serializers module from Django REST Framework (DRF) to handle data conversion.

class ItemSerializer(serializers.Serializer):
    """
    ITEM SERIALIZER
    
    Analogy:
    Think of a Serializer like a translator at a customs desk.
    Our database stores raw records, but the frontend needs them as standard JSON text.
    The Serializer translates our Python database objects into clean JSON dictionaries,
    and checks if incoming user data is valid before saving it.
    """
    
    # id: The unique database primary key. Read-only because it's automatically generated by Django.
    id = serializers.IntegerField(read_only=True)
    
    # name: The name of the tech gadget.
    name = serializers.CharField()
    
    # brand: The manufacturer of the gadget.
    brand = serializers.CharField()
    
    # category: The type of gadget, e.g., Headphones, Laptops, or Cameras.
    category = serializers.CharField()
    
    # description: A detailed description explaining the gadget's specifications.
    description = serializers.CharField()
    
    # image_url: A web link pointing to the product cover image.
    image_url = serializers.CharField(required=False, allow_blank=True)
    
    # price: The listed price. We specify max_digits and decimal_places to preserve decimal formatting.
    price = serializers.DecimalField(max_digits=10, decimal_places=2)
    
    # avg_rating: The average rating score (1-5) calculated dynamically across all reviews.
    # We use FloatField since it can contain decimals (e.g. 4.5) and allow_null=True if there are no reviews yet.
    avg_rating = serializers.FloatField(allow_null=True)
    
    # review_count: The total count of reviews written for this specific gadget.
    review_count = serializers.IntegerField()
